added for you page and template journals on the centralized feed (#29)
* added for you page and template journals on the centralized feed

* Try double quoting prettier execution

* fix test for prettier

* Only suggest changes when there changes

* Fix prettier execution in GitHub workflow

* Fix prettier workflow

* fix prettier action

* * Write prettier output to file instead

* Fix suggestions action

* * fix again :(

* quote GH comment
use environmental for suggest-changes

* * Remove conditional

* * Run commit when prettier write succeeds

* * Use outcome instead of conclusion

* Run commit action if any previous steps failed

* bump suggest changes ver

* final try

* Disabled suggest action

* prettified

* Change line ending to windows

* Fix ORM (Sorry again everyone)

* Add spalsh screen icon

* Fixed debug menu causing unresponsiveness. Added image capturing

* Add image capturing feature and full preview functionality

* Add ImageGallery functionality

* Add audio recording and playback functionality

* added for you page and template journals on the centralized feed

* Try double quoting prettier execution

* fix test for prettier

* Only suggest changes when there changes

* Fix prettier execution in GitHub workflow

* Fix prettier workflow

* fix prettier action

* * Write prettier output to file instead

* Fix suggestions action

* * fix again :(

* quote GH comment
use environmental for suggest-changes

* * Remove conditional

* * Run commit when prettier write succeeds

* * Use outcome instead of conclusion

* Run commit action if any previous steps failed

* bump suggest changes ver

* final try

* Disabled suggest action

* prettified

* Move fake stories to preexisting constants dir

* Make card generation dynamic

* Componentize Image preview

---------

Co-authored-by: ehharvey <eharvey3704@conestogac.on.ca>
Co-authored-by: Cole Foster <cole@thefostersonline.com>
Co-authored-by: Cole Foster <71045117+colefoster@users.noreply.github.com>

diff --git a/.github/workflows/prettier.yml b/.github/workflows/prettier.yml
--- a/.github/workflows/prettier.yml
+++ b/.github/workflows/prettier.yml
@@ -26,28 +26,25 @@ jobs:
       - name: Run Prettier
         id: prettier
         run: |
-          {
-            echo 'PRETTIER<<EOF'
-            npx prettier --check **/*.tsx 
-            echo 'EOF'
-          } >> "$GITHUB_ENV"
+          npx prettier --check **/*.tsx > prettier.txt
+          echo "prettier_exit=$?" >> "$GITHUB_ENV"
         
         
       - name: Add comment
-        run: gh issue comment "$NUMBER" --body "$PRETTIER"
+        run: gh issue comment "$NUMBER" --body "$(cat prettier.txt)"
         if: always()
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           GH_REPO: ${{ github.repository }}
           NUMBER: ${{ github.event.pull_request.number }}
 
-      - name: Run Prettier but write changes
-        run: npx prettier --write **/*.tsx 
+      # DOES NOT WORK 2024-04-08
+      # - name: Run Prettier but write changes
+      #   run: npx prettier --write **/*.tsx 
+      #   id: prettier-write
+      #   if: always()
 
-        if: always()
-        
-
-      - uses: parkerbxyz/suggest-changes@v1
-        if: always()
-        with:
-          comment: 'Please commit the suggested changes from prettier :p.'
+      # - uses: parkerbxyz/suggest-changes@v1.0.3
+      #   if: ${{ steps.prettier-write.outcome == 'success' && failure() }}
+      #   with:
+      #     comment: 'Please commit the suggested changes from prettier :p.'
